services:
  - type: web
    name: school-cab-api
    env: docker
    region: singapore
    plan: free
    startCommand: sh -c "php artisan migrate --force && apache2-foreground"
    envVars:
      - key: APP_KEY
        sync: false
      - key: APP_DEBUG
        value: false
      - key: APP_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: school-cab-db
          property: connectionString

databases:
  - name: school-cab-db
    region: singapore
    plan: free
    databaseName: school_cab
    user: school_cab_user
